### ISSUE TITLE
offset compression

### ISSUE THREAD

**Issue by keizo042** [keizo042/mruby-resolv#6]

**Comment by keizo042** [comment]
add offset check.
check by test

**Comment by take-cheeze** [comment]
マスク0xC0のアレ。
意図しない終端のエラーハンドリングがめんどくさい。

**Comment by take-cheeze** [comment]
あと、意図しない終端だとデータ的にアレなのでinvalid data的な例外でよいのでは

**Comment by take-cheeze** [comment]
パソコン教室のくせに割りといい解説
http://park12.wakwak.com/~eslab/pcmemo/dns/dns4.html#condense

**Comment by keizo042** [comment]
> あと、意図しない終端だとデータ的にアレなのでinvalid data的な例外でよいのでは

まず、意図しない終端はraiseで良い。

> マスク0xC0のアレ。

`mrb_dns_name_t *mrb_dns_codec_get_name(mrb_state *, mrb_dns_get_state*)`と
`mrb_dns_name_t *mrb_dns_codec_get_name_by_offset(mrb_state *mrb, mrb_dns_get_state*, uint16_t)`
のように、通常のFQDN取得関数とoffsetで取得する関数を実装して、  
相互再帰させればだいたい問題ないと思う。

**Comment by keizo042** [comment]
直した #14
